"""initial

Revision ID: 2a99e251619c
Revises: 
Create Date: 2026-09-11 02:17:59.957425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a99e251619c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solar_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('site_address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('num_panels', sa.Integer(), nullable=True),
    sa.Column('panel_wattage', sa.Float(), nullable=True),
    sa.Column('panel_model', sa.String(), nullable=True),
    sa.Column('inverter_model', sa.String(), nullable=True),
    sa.Column('roof_area_sqm', sa.Float(), nullable=True),
    sa.Column('degradation_rate', sa.Float(), nullable=True),
    sa.Column('temp_loss_pct', sa.Float(), nullable=True),
    sa.Column('shading_loss_pct', sa.Float(), nullable=True),
    sa.Column('soiling_loss_pct', sa.Float(), nullable=True),
    sa.Column('inverter_loss_pct', sa.Float(), nullable=True),
    sa.Column('mismatch_loss_pct', sa.Float(), nullable=True),
    sa.Column('dc_wiring_loss_pct', sa.Float(), nullable=True),
    sa.Column('ac_wiring_loss_pct', sa.Float(), nullable=True),
    sa.Column('capacity_kwp', sa.Float(), nullable=True),
    sa.Column('annual_gen_kwh', sa.Float(), nullable=True),
    sa.Column('specific_yield', sa.Float(), nullable=True),
    sa.Column('performance_ratio', sa.Float(), nullable=True),
    sa.Column('total_system_loss', sa.Float(), nullable=True),
    sa.Column('lifetime_gen_mwh', sa.Float(), nullable=True),
    sa.Column('year25_output_mwh', sa.Float(), nullable=True),
    sa.Column('monthly_gen_json', sa.Text(), nullable=True),
    sa.Column('is_calculated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solar_projects_client_name'), 'solar_projects', ['client_name'], unique=False)
    op.create_index(op.f('ix_solar_projects_id'), 'solar_projects', ['id'], unique=False)
    op.create_index(op.f('ix_solar_projects_project_name'), 'solar_projects', ['project_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solar_projects_project_name'), table_name='solar_projects')
    op.drop_index(op.f('ix_solar_projects_id'), table_name='solar_projects')
    op.drop_index(op.f('ix_solar_projects_client_name'), table_name='solar_projects')
    op.drop_table('solar_projects')
    # ### end Alembic commands ###
